#! /usr/bin/env bash

# vim:filetype=sh
if [[ "x$TODO" = "x" ]]; then
  BADOOP=~/.todo.txt
else
  BADOOP="$TODO"
fi

function badoop_usage() {
  echo "badoop"
  echo "  -h: print this help"
  echo "  -d: delete any todo items matching remaining arguments"
  echo "  -i, --indent:  indent any todo items matching remaining arguments"
  echo "  -u, --unindent: un-indent any todo items matching remaining arguments"
  echo "  with no flags: add the string passed in to the todo list"
  echo "  with no arguments: print out todo list"
}

# Badoop-done. Delete from todo list
function badone() {
  # $@ is all the arguments passed in.
  # not sure what d is. Flag to delete anything that matches?

  if [[ -f "$BADOOP" ]]; then
    sed -i -e "/$@/d" "$BADOOP";
  fi
}

# Badoop-indent. Indent or un-indent an item
function badoopindent() {
  # $1 indicates the indent direction
  # The rest of $@ has the item search regex

  if [[ -f "$BADOOP" ]]; then
    if [[ $1 == "i" ]]; then
      shift
      sed -i -e "/$@/s/^/    /" "$BADOOP";
    elif [[ $1 == "u" ]]; then
      shift
      sed -i -e "/$@/s/^    //" "$BADOOP";
    fi
  fi
}

function badoop() {
  # $# is the number of parameters passed in
  # command with no args just shows all todos

  if [[ $# == "0" ]]; then
    if [[ -f "$BADOOP" ]]; then
      cat "$BADOOP";
    fi
  elif [[ $1 == "-h" ]]; then
    badoop_usage
  elif [[ $1 == "-d" ]]; then
    shift
    badone $@
  elif [[ $1 == "-u" || $1 == "--unindent" ]]; then
    shift
    badoopindent "u" $@
  elif [[ $1 == "-i" || $1 == "--indent" ]]; then
    shift
    badoopindent "i" $@
  else
    # adding a new todo
    # $@ is a string containing all parameters
    echo "  • $@" >> "$BADOOP"
  fi
}

badoop $@
